//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknolojiBlogMVC.Models.entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_comment
    {
        public int CommentId { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Blog { get; set; }
        public Nullable<bool> Confirmation { get; set; }
    
        public virtual tbl_blog tbl_blog { get; set; }
    }
}
