//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknolojiBlogMVC.Models.entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_about
    {
        public int Id { get; set; }
        public string About { get; set; }
        public string PhotoUrl { get; set; }
        public string About2 { get; set; }
        public string PhotoUrl2 { get; set; }
        public string About3 { get; set; }
        public string PhotoUrl3 { get; set; }
    }
}
