//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknolojiBlogMVC.Models.entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_blog()
        {
            this.tbl_comment = new HashSet<tbl_comment>();
        }
    
        public int BlogId { get; set; }
        public string Title { get; set; }
        public string PhotoUrl { get; set; }
        public string ReleaseDate { get; set; }
        public string BlogContent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_comment> tbl_comment { get; set; }
    }
}
